window.esdocSearchIndex = [
  [
    "pgf-model/source/auth.js~auth",
    "class/source/auth.js~Auth.html",
    "<span>Auth</span> <span class=\"search-result-import-path\">pgf-model/source/auth.js</span>",
    "class"
  ],
  [
    "pgf-model/source/channels.js~channelfactory",
    "class/source/channels.js~ChannelFactory.html",
    "<span>ChannelFactory</span> <span class=\"search-result-import-path\">pgf-model/source/channels.js</span>",
    "class"
  ],
  [
    "pgf-model/source/deviceinfo.js~device",
    "class/source/deviceInfo.js~Device.html",
    "<span>Device</span> <span class=\"search-result-import-path\">pgf-model/source/deviceInfo.js</span>",
    "class"
  ],
  [
    "pgf-model/source/model.js~model",
    "class/source/model.js~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">pgf-model/source/model.js</span>",
    "class"
  ],
  [
    "pgf-model/source/observer.js~observer",
    "class/source/Observer.js~Observer.html",
    "<span>Observer</span> <span class=\"search-result-import-path\">pgf-model/source/Observer.js</span>",
    "class"
  ],
  [
    "pgf-model/source/pubsub.js~pubsub",
    "class/source/pubsub.js~PubSub.html",
    "<span>PubSub</span> <span class=\"search-result-import-path\">pgf-model/source/pubsub.js</span>",
    "class"
  ],
  [
    "pgf-model/source/request.js~request",
    "class/source/request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">pgf-model/source/request.js</span>",
    "class"
  ],
  [
    "pgf-model/source/channels.js~channelfactory",
    "variable/index.html#static-variable-channelFactory",
    "<span>channelFactory</span> <span class=\"search-result-import-path\">pgf-model/source/channels.js</span>",
    "variable"
  ],
  [
    "pgf-model/source/utils.js~isequal",
    "function/index.html#static-function-isEqual",
    "<span>isEqual</span> <span class=\"search-result-import-path\">pgf-model/source/utils.js</span>",
    "function"
  ],
  [
    "pgf-model/source/utils.js~isobject",
    "function/index.html#static-function-isObject",
    "<span>isObject</span> <span class=\"search-result-import-path\">pgf-model/source/utils.js</span>",
    "function"
  ],
  [
    "pgf-model/source/utils.js~isundefined",
    "function/index.html#static-function-isUndefined",
    "<span>isUndefined</span> <span class=\"search-result-import-path\">pgf-model/source/utils.js</span>",
    "function"
  ],
  [
    "pgf-model/source/listento.js~listento",
    "function/index.html#static-function-listenTo",
    "<span>listenTo</span> <span class=\"search-result-import-path\">pgf-model/source/listenTo.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/AuthTest.js.html#lineNumber3",
    "Testing Auth",
    "test"
  ],
  [
    "",
    "test-file/test/AuthTest.js.html#lineNumber8",
    "Testing Auth Instance sould be object",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber5",
    "Testing Model",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber10",
    "Testing Model Instance sould be object",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber6",
    "Testing Model Model sould be function",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber77",
    "Testing Model Testing Model Defaults",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber90",
    "Testing Model Testing Model Defaults Default argument should be object",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber110",
    "Testing Model Testing Model Defaults Default is not dispatching an event",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber100",
    "Testing Model Testing Model Defaults Default is only one argument",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber119",
    "Testing Model Testing Model Defaults Will not dispatch an event if setted with the same value",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber82",
    "Testing Model Testing Model Defaults should create a model",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber86",
    "Testing Model Testing Model Defaults should get the default",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber15",
    "Testing Model Testing Model Instance",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber39",
    "Testing Model Testing Model Instance can be changed",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber45",
    "Testing Model Testing Model Instance it dispatches ONE event when set ONCE",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber64",
    "Testing Model Testing Model Instance it is not dispatching an event when called with silent option",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber54",
    "Testing Model Testing Model Instance it is not dispatching an event when set twice with the same value",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber34",
    "Testing Model Testing Model Instance should be able to get",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber20",
    "Testing Model Testing Model Instance should be able to set",
    "test"
  ],
  [
    "",
    "test-file/test/ModelTest.js.html#lineNumber24",
    "Testing Model Testing Model Instance should trow an error if key is missing",
    "test"
  ],
  [
    "",
    "test-file/test/requestTest.js.html#lineNumber3",
    "Testing Request",
    "test"
  ],
  [
    "",
    "test-file/test/requestTest.js.html#lineNumber12",
    "Testing Request Instance sould be object",
    "test"
  ],
  [
    "",
    "test-file/test/requestTest.js.html#lineNumber8",
    "Testing Request Should create the request Instance",
    "test"
  ],
  [
    "",
    "test-file/test/channelsTest.js.html#lineNumber3",
    "Testing channels:",
    "test"
  ],
  [
    "",
    "test-file/test/channelsTest.js.html#lineNumber24",
    "Testing channels: can call a method",
    "test"
  ],
  [
    "",
    "test-file/test/channelsTest.js.html#lineNumber12",
    "Testing channels: can create a new channel via getChannel method",
    "test"
  ],
  [
    "",
    "test-file/test/channelsTest.js.html#lineNumber16",
    "Testing channels: can publish",
    "test"
  ],
  [
    "",
    "test-file/test/channelsTest.js.html#lineNumber20",
    "Testing channels: can subscribe",
    "test"
  ],
  [
    "",
    "test-file/test/channelsTest.js.html#lineNumber8",
    "Testing channels: channels can be imported",
    "test"
  ],
  [
    "",
    "test-file/test/channelsTest.js.html#lineNumber32",
    "Testing channels: triggers the callback only on a subscribed channel",
    "test"
  ],
  [
    "",
    "test-file/test/listenToTest.js.html#lineNumber4",
    "Testing listenTo:",
    "test"
  ],
  [
    "",
    "test-file/test/listenToTest.js.html#lineNumber9",
    "Testing listenTo: listentTo can be imported",
    "test"
  ],
  [
    "",
    "test-file/test/listenToTest.js.html#lineNumber13",
    "Testing listenTo: listentTo can be used with a model",
    "test"
  ],
  [
    "",
    "test-file/test/listenToTest.js.html#lineNumber17",
    "Testing listenTo: model param should be a Model instance",
    "test"
  ],
  [
    "",
    "test-file/test/listenToTest.js.html#lineNumber35",
    "Testing listenTo: should NOT call a function if it is not listening for the proper key",
    "test"
  ],
  [
    "",
    "test-file/test/listenToTest.js.html#lineNumber28",
    "Testing listenTo: should call a callback function",
    "test"
  ],
  [
    "source/observer.js",
    "file/source/Observer.js.html",
    "source/Observer.js",
    "file"
  ],
  [
    "source/observer.js~observer#addobserver",
    "class/source/Observer.js~Observer.html#instance-method-addObserver",
    "source/Observer.js~Observer#addObserver",
    "method"
  ],
  [
    "source/observer.js~observer#constructor",
    "class/source/Observer.js~Observer.html#instance-constructor-constructor",
    "source/Observer.js~Observer#constructor",
    "method"
  ],
  [
    "source/observer.js~observer#notify",
    "class/source/Observer.js~Observer.html#instance-method-notify",
    "source/Observer.js~Observer#notify",
    "method"
  ],
  [
    "source/observer.js~observer#observers",
    "class/source/Observer.js~Observer.html#instance-member-observers",
    "source/Observer.js~Observer#observers",
    "member"
  ],
  [
    "source/app.js",
    "file/source/app.js.html",
    "source/app.js",
    "file"
  ],
  [
    "source/auth.js",
    "file/source/auth.js.html",
    "source/auth.js",
    "file"
  ],
  [
    "source/auth.js~auth#getgameinfo",
    "class/source/auth.js~Auth.html#instance-method-getGameInfo",
    "source/auth.js~Auth#getGameInfo",
    "method"
  ],
  [
    "source/channels.js",
    "file/source/channels.js.html",
    "source/channels.js",
    "file"
  ],
  [
    "source/channels.js~channelfactory#constructor",
    "class/source/channels.js~ChannelFactory.html#instance-constructor-constructor",
    "source/channels.js~ChannelFactory#constructor",
    "method"
  ],
  [
    "source/channels.js~channelfactory#getchannel",
    "class/source/channels.js~ChannelFactory.html#instance-method-getChannel",
    "source/channels.js~ChannelFactory#getChannel",
    "method"
  ],
  [
    "source/deviceinfo.js",
    "file/source/deviceInfo.js.html",
    "source/deviceInfo.js",
    "file"
  ],
  [
    "source/deviceinfo.js~device#clickevent",
    "class/source/deviceInfo.js~Device.html#instance-member-clickEvent",
    "source/deviceInfo.js~Device#clickEvent",
    "member"
  ],
  [
    "source/deviceinfo.js~device#constructor",
    "class/source/deviceInfo.js~Device.html#instance-constructor-constructor",
    "source/deviceInfo.js~Device#constructor",
    "method"
  ],
  [
    "source/deviceinfo.js~device#detectdevice",
    "class/source/deviceInfo.js~Device.html#instance-method-detectDevice",
    "source/deviceInfo.js~Device#detectDevice",
    "method"
  ],
  [
    "source/deviceinfo.js~device#has3dtransforms",
    "class/source/deviceInfo.js~Device.html#instance-method-has3DTransforms",
    "source/deviceInfo.js~Device#has3DTransforms",
    "method"
  ],
  [
    "source/deviceinfo.js~device#isandroid23device",
    "class/source/deviceInfo.js~Device.html#instance-member-isAndroid23Device",
    "source/deviceInfo.js~Device#isAndroid23Device",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isandroid3tablet",
    "class/source/deviceInfo.js~Device.html#instance-member-isAndroid3Tablet",
    "source/deviceInfo.js~Device#isAndroid3Tablet",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isandroid400",
    "class/source/deviceInfo.js~Device.html#instance-member-isAndroid400",
    "source/deviceInfo.js~Device#isAndroid400",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isandroid410",
    "class/source/deviceInfo.js~Device.html#instance-member-isAndroid410",
    "source/deviceInfo.js~Device#isAndroid410",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isandroid420",
    "class/source/deviceInfo.js~Device.html#instance-member-isAndroid420",
    "source/deviceInfo.js~Device#isAndroid420",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isandroid430",
    "class/source/deviceInfo.js~Device.html#instance-member-isAndroid430",
    "source/deviceInfo.js~Device#isAndroid430",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isandroiddevice",
    "class/source/deviceInfo.js~Device.html#instance-member-isAndroidDevice",
    "source/deviceInfo.js~Device#isAndroidDevice",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isandroidtablet",
    "class/source/deviceInfo.js~Device.html#instance-member-isAndroidTablet",
    "source/deviceInfo.js~Device#isAndroidTablet",
    "member"
  ],
  [
    "source/deviceinfo.js~device#ischrome",
    "class/source/deviceInfo.js~Device.html#instance-member-isChrome",
    "source/deviceInfo.js~Device#isChrome",
    "member"
  ],
  [
    "source/deviceinfo.js~device#ischrome280",
    "class/source/deviceInfo.js~Device.html#instance-member-isChrome280",
    "source/deviceInfo.js~Device#isChrome280",
    "member"
  ],
  [
    "source/deviceinfo.js~device#ischromeforios",
    "class/source/deviceInfo.js~Device.html#instance-member-isChromeForIOS",
    "source/deviceInfo.js~Device#isChromeForIOS",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isdesktop",
    "class/source/deviceInfo.js~Device.html#instance-member-isDesktop",
    "source/deviceInfo.js~Device#isDesktop",
    "member"
  ],
  [
    "source/deviceinfo.js~device#ishtcone",
    "class/source/deviceInfo.js~Device.html#instance-member-isHTCOne",
    "source/deviceInfo.js~Device#isHTCOne",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiniframe",
    "class/source/deviceInfo.js~Device.html#instance-member-isInIFrame",
    "source/deviceInfo.js~Device#isInIFrame",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiphone3gs",
    "class/source/deviceInfo.js~Device.html#instance-member-isIphone3GS",
    "source/deviceInfo.js~Device#isIphone3GS",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiphone4or4s",
    "class/source/deviceInfo.js~Device.html#instance-member-isIphone4Or4s",
    "source/deviceInfo.js~Device#isIphone4Or4s",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiphone5or5sor5c",
    "class/source/deviceInfo.js~Device.html#instance-member-isIphone5Or5sOr5c",
    "source/deviceInfo.js~Device#isIphone5Or5sOr5c",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isonex",
    "class/source/deviceInfo.js~Device.html#instance-member-isOneX",
    "source/deviceInfo.js~Device#isOneX",
    "member"
  ],
  [
    "source/deviceinfo.js~device#issafari",
    "class/source/deviceInfo.js~Device.html#instance-member-isSafari",
    "source/deviceInfo.js~Device#isSafari",
    "member"
  ],
  [
    "source/deviceinfo.js~device#issamsungs",
    "class/source/deviceInfo.js~Device.html#instance-member-isSamsungS",
    "source/deviceInfo.js~Device#isSamsungS",
    "member"
  ],
  [
    "source/deviceinfo.js~device#istouchdevice",
    "class/source/deviceInfo.js~Device.html#instance-member-isTouchDevice",
    "source/deviceInfo.js~Device#isTouchDevice",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isios9",
    "class/source/deviceInfo.js~Device.html#instance-member-isiOS9",
    "source/deviceInfo.js~Device#isiOS9",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiosdevice",
    "class/source/deviceInfo.js~Device.html#instance-member-isiOSDevice",
    "source/deviceInfo.js~Device#isiOSDevice",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isipad",
    "class/source/deviceInfo.js~Device.html#instance-member-isiPad",
    "source/deviceInfo.js~Device#isiPad",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiphone",
    "class/source/deviceInfo.js~Device.html#instance-member-isiPhone",
    "source/deviceInfo.js~Device#isiPhone",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiphoneios7",
    "class/source/deviceInfo.js~Device.html#instance-member-isiPhoneIOS7",
    "source/deviceInfo.js~Device#isiPhoneIOS7",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiphoneios8",
    "class/source/deviceInfo.js~Device.html#instance-member-isiPhoneIOS8",
    "source/deviceInfo.js~Device#isiPhoneIOS8",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isiphoneios9",
    "class/source/deviceInfo.js~Device.html#instance-member-isiPhoneIOS9",
    "source/deviceInfo.js~Device#isiPhoneIOS9",
    "member"
  ],
  [
    "source/deviceinfo.js~device#isipod",
    "class/source/deviceInfo.js~Device.html#instance-member-isiPod",
    "source/deviceInfo.js~Device#isiPod",
    "member"
  ],
  [
    "source/deviceinfo.js~device#touchendevent",
    "class/source/deviceInfo.js~Device.html#instance-member-touchendEvent",
    "source/deviceInfo.js~Device#touchendEvent",
    "member"
  ],
  [
    "source/deviceinfo.js~device#touchmoveevent",
    "class/source/deviceInfo.js~Device.html#instance-member-touchmoveEvent",
    "source/deviceInfo.js~Device#touchmoveEvent",
    "member"
  ],
  [
    "source/deviceinfo.js~device#touchoutevent",
    "class/source/deviceInfo.js~Device.html#instance-member-touchoutEvent",
    "source/deviceInfo.js~Device#touchoutEvent",
    "member"
  ],
  [
    "source/deviceinfo.js~device#touchstartevent",
    "class/source/deviceInfo.js~Device.html#instance-member-touchstartEvent",
    "source/deviceInfo.js~Device#touchstartEvent",
    "member"
  ],
  [
    "source/deviceinfo.js~device#uselegacyscaling",
    "class/source/deviceInfo.js~Device.html#instance-member-useLegacyScaling",
    "source/deviceInfo.js~Device#useLegacyScaling",
    "member"
  ],
  [
    "source/es6examples.js",
    "file/source/es6examples.js.html",
    "source/es6examples.js",
    "file"
  ],
  [
    "source/listento.js",
    "file/source/listenTo.js.html",
    "source/listenTo.js",
    "file"
  ],
  [
    "source/model.js",
    "file/source/model.js.html",
    "source/model.js",
    "file"
  ],
  [
    "source/model.js~model#constructor",
    "class/source/model.js~Model.html#instance-constructor-constructor",
    "source/model.js~Model#constructor",
    "method"
  ],
  [
    "source/model.js~model#get",
    "class/source/model.js~Model.html#instance-method-get",
    "source/model.js~Model#get",
    "method"
  ],
  [
    "source/model.js~model#pubsub",
    "class/source/model.js~Model.html#instance-get-pubsub",
    "source/model.js~Model#pubsub",
    "member"
  ],
  [
    "source/model.js~model#set",
    "class/source/model.js~Model.html#instance-method-set",
    "source/model.js~Model#set",
    "method"
  ],
  [
    "source/oldapp.js",
    "file/source/oldapp.js.html",
    "source/oldapp.js",
    "file"
  ],
  [
    "source/pubsub.js",
    "file/source/pubsub.js.html",
    "source/pubsub.js",
    "file"
  ],
  [
    "source/pubsub.js~pubsub#constructor",
    "class/source/pubsub.js~PubSub.html#instance-constructor-constructor",
    "source/pubsub.js~PubSub#constructor",
    "method"
  ],
  [
    "source/pubsub.js~pubsub#publish",
    "class/source/pubsub.js~PubSub.html#instance-method-publish",
    "source/pubsub.js~PubSub#publish",
    "method"
  ],
  [
    "source/pubsub.js~pubsub#subuid",
    "class/source/pubsub.js~PubSub.html#instance-member-subUid",
    "source/pubsub.js~PubSub#subUid",
    "member"
  ],
  [
    "source/pubsub.js~pubsub#subscribe",
    "class/source/pubsub.js~PubSub.html#instance-method-subscribe",
    "source/pubsub.js~PubSub#subscribe",
    "method"
  ],
  [
    "source/pubsub.js~pubsub#topics",
    "class/source/pubsub.js~PubSub.html#instance-member-topics",
    "source/pubsub.js~PubSub#topics",
    "member"
  ],
  [
    "source/pubsub.js~pubsub#unsubscribe",
    "class/source/pubsub.js~PubSub.html#instance-method-unsubscribe",
    "source/pubsub.js~PubSub#unsubscribe",
    "method"
  ],
  [
    "source/request.js",
    "file/source/request.js.html",
    "source/request.js",
    "file"
  ],
  [
    "source/request.js~request#get",
    "class/source/request.js~Request.html#instance-method-get",
    "source/request.js~Request#get",
    "method"
  ],
  [
    "source/request.js~request#post",
    "class/source/request.js~Request.html#instance-method-post",
    "source/request.js~Request#post",
    "method"
  ],
  [
    "source/utils.js",
    "file/source/utils.js.html",
    "source/utils.js",
    "file"
  ],
  [
    "test/authtest.js",
    "test-file/test/AuthTest.js.html",
    "test/AuthTest.js",
    "testFile"
  ],
  [
    "test/modeltest.js",
    "test-file/test/ModelTest.js.html",
    "test/ModelTest.js",
    "testFile"
  ],
  [
    "test/channelstest.js",
    "test-file/test/channelsTest.js.html",
    "test/channelsTest.js",
    "testFile"
  ],
  [
    "test/listentotest.js",
    "test-file/test/listenToTest.js.html",
    "test/listenToTest.js",
    "testFile"
  ],
  [
    "test/requesttest.js",
    "test-file/test/requestTest.js.html",
    "test/requestTest.js",
    "testFile"
  ]
]